name: SkinFixer
main: dev.array21.skinfixer.SkinFixer
version: @version@
author: Dutchy76
api-version: 1.16
commands:
  skin:
    description: SkinFixer's main command
  setskin:
    description: Set a skin directly from a URL

permissions:
  skinfixer.get:
    default: true
  skinfixer.reload:
    default: op
  skinfixer.reset:
    default: true
  skinfixer.set:
    default: true
  skinfixer.version:
    default: op